# Generated by Django 5.2.7 on 2025-11-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactApp", "0002_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="birth",
            field=models.DateField(
                default="2025-11-06", max_length=20, verbose_name="出生日期"
            ),
        ),
    ]
